# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: aws
    resourceType: VirtualMachine
    tags: web # only deploy to virtual machines with this tag
  strategy:
    runOnce:
      deploy:   
          steps:
          - script: cd /home/ubuntu && ls
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                echo $SOME_VAR >> /home/ubuntu/gopa.txt
              workingDirectory: '/home/ubuntu/xyita'
